version: 0.1
 
phases:
  pre_build:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet build
artifacts:
  files:
    - bin/Debug/netcoreapp1.1/*
  discard-paths: yes
